---
title: "analise_rais_real"
description: |
  Objetivo: Analisar os salários na base da RAIS.
author:
  - name: Amanda Rabelo
    url: https://example.com/norajones
date: 2021-12-08
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Nesse relatório estamos interessados em responder:

"Quanto ganha um cientista de dados?"

Para isso vamos utilizar uma base da RAIS anonimizada. 

Vamos utilizar o [datalake da iniciativa base de dados]
(https://basedosdados.org/). 

Carregando as cinco primeiras linhas da tabela microdados.

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#Packages 

library("bigrquery")
library("dplyr")
library("DBI")

```

#Acessando os dados da RAIS

```{r}

# O normal seria assim 

# tabela_normal <- read.csv(
#   "https://raw.githubusercontent.com/curso-r/main-r4ds-1/master/dados/imdb.csv"
# )
# 
# head(tabela_normal,5)


# Usando SGBD 

conexao <- dbConnect(
  bigquery(),
  project = "basedosdados",
  dataset = "br_me_rais",
  billing = "projeto1-334519"
)


primeiro_cinco_linhas <- collect(head(select(tbl(conexao, "microdados_vinculos"), everything()),5))
```


Learn more about using Distill at <https://rstudio.github.io/distill>.


